### ISSUE TITLE
Latest update doesn't work in IE, and isn't getting transpiled by Babel

### ISSUE THREAD

**Issue by JacobDB** [hpohlmeyer/in-vp#2]
Seems to not like the arrow function at the top of the file, not sure why it's not being transpiled. Will try to take a look when I have some time and report back.

**Comment by hpohlmeyer** [comment]
Hey, thanks for letting me know.  
I have tried to compile both, the module version and the js version with Babel and it seems to work fine. Do you have an example that I could check out?

But while trying it I realized, that the mjs export was faulty. This is fixed in v1.1.1 now. Could you give it a shot and see if it helps with your issue in any way?

**Comment by JacobDB** [comment]
Strange, I'm getting this when compiling with webpack (on v1.1.1):

```js
/***/ "./node_modules/in-vp/dist/index.mjs":
/*!*******************************************!*\
  !*** ./node_modules/in-vp/dist/index.mjs ***!
  \*******************************************/
/*! exports provided: default */
/***/ (function(__webpack_module__, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony default export */ __webpack_exports__["default"] = ((t,o={})=>{const l=Object.assign({top:0,right:0,bottom:0,left:0},o),e=document.documentElement.clientWidth,i=document.documentElement.clientHeight,r=t.getBoundingClientRect(),{top:f,left:g,width:m,height:p}=r,h=e-r.right,b=i-r.bottom,n={top:f<l.top,left:g<l.left,bottom:b<l.bottom,right:h<l.right},a={top:n.top&&f>-p+l.top,left:n.left&&g>-m+l.left,bottom:n.bottom&&b>-p+l.bottom,right:n.right&&h>-m+l.right},u=f>=l.top&&h>=l.right&&b>=l.bottom&&g>=l.left,y=a.top||a.right||a.bottom||a.left;return{fully:u,partially:y,edges:{top:(u||y)&&(n.top||n.left||n.right?!n.top&&"partially":"fully")||!1,right:(u||y)&&(n.right||n.top||n.bottom?!n.right&&"partially":"fully")||!1,bottom:(u||y)&&(n.bottom||n.left||n.right?!n.bottom&&"partially":"fully")||!1,left:(u||y)&&(n.left||n.top||n.bottom?!n.left&&"partially":"fully")||!1}}});
```

I use plenty of other arrow functions in my code, so no clue why this one in particular is causing trouble. My Babel settings for Webpack are below.

```js
{
    test: /\.js$/,
    use: {
        loader: "babel-loader",
        options: {
            presets: ["@babel/preset-env"],
        },
    },
},
```

Using:

- @babel/core v7.5.5
- @babel/preset-env v7.5.5
- babel-loader v8.0.6
- in-vp v1.1.1
- webpack v4.39.1

https://github.com/JacobDB/new-site/blob/master/webpack.config.js

**Comment by hpohlmeyer** [comment]
Webpack is using the `.mjs` file over the `.js` file. Try adding it to your test regex:

```js
{
    test: /\.m?js$/,
    use: {
        loader: "babel-loader",
        options: {
            presets: ["@babel/preset-env"],
        },
    },
},
```

if that still does not work, you may need to explicitly include the module, although that was not necessary when I was testing it.

```js
include: [
  path.resolve('src'),
  path.join(__dirname, 'node_modules', 'in-vp')
],
```

---

I will examine the babel output tomorrow, if I find some time. If it is just the arrow function that prevents full IE support, I will change it.

**Comment by JacobDB** [comment]
Ah, interesting, thanks. I'm out of the office until Monday but will give that a shot.

**Comment by JacobDB** [comment]
Beautiful, changing my regex fixed it. Was going to say that the instructions from Babel/Webpack say nothing about that, but clearly [they do](https://webpack.js.org/loaders/babel-loader/#usage), so I'm just dumb 😅. Thanks for the assistance!
